#!/bin/bash

UPDATE=1
TEXTCOL="#aaaa00"

MUSIC_ICONCOL="#cc6633"
VOLUME_ICONCOL="#606060"
SEPCOL="#707070"

LCOR="^i(/home/cas/.xmonad/dzen2/icons/myicons/corner-left.xbm)"
RCOR="^i(/home/cas/.xmonad/dzen2/icons/myicons/corner-right.xbm)"
ICON="^i(/home/cas/.xmonad/dzen2/icons/mpd.xbm)"
PLAY="^i(/home/cas/.dwm/dzen2/icons/dzen_bitmaps/play.xbm)"
PAUSE="^i(/home/cas/.dwm/dzen2/icons/dzen_bitmaps/pause.xbm)"
COUNT=0

function pad { 
    C=0
    while [ "$C" -lt $1 ]; do
	echo -n " "
	C=$(( $C + 1 ))
    done
    echo -n "^bg()"
}

function outputinfo {
        STRLEN=$(expr length "$1 $2" )
	PAD=$(( 41 - $STRLEN ))
	echo -n "^fg(#242424)$LCOR^bg(#242424)^fg(#707070)$1 ^fg(#aaaaaa)$2^fg()"
	pad $PAD
	echo -n "^bg()^fg(#242424)$RCOR"
}

while :;  do

    sleep $UPDATE;
    echo -n "^fg(#000000)$LCOR^bg(#000000)^fg(#fff)MPD:^bg()^fg(#000000)$RCOR" # main label
    
    # check if daemon is running
    STATE=$(mpc | grep "\[")

    # if mpd isn't running, display padded module with info
    if [ "$STATE" = "" ]; then 
	echo -n "^fg(#242424)$LCOR^bg(#242424)^fg(#707070)Stopped...^fg()"
	pad 60 # padding that makes module same length as when mpd is running
	echo  "^bg()^fg(#242424)$RCOR"

    else # mpd is running
	ARTIST=$(mpc -f %artist% | head -n 1) # grab artist name

	ALBUM=$(mpc -f %album% | head -n 1 | sed -e 's/é/e/') # grab album name
	STRLEN=$(expr length "$ALBUM") # restrict length
	if [ $STRLEN  -gt 25 ]; then
		ALBUM="${ALBUM:0:25}..."
	fi

	TRACK=$(mpc -f %track% | head -n 1) # grab track nr
	TITLE=`mpc -f %title% | head -n 1 | sed -e 's/\[//' | sed -e 's/\]//' | sed -e 's/é/e/'` # grab song title
	SONG="$TRACK - $TITLE" # combine
	STRLEN=$(expr length "$SONG") # restrict length (+1 for shorter label)
	if [ $STRLEN  -gt 26 ]; then
		SONG="${SONG:0:26}..."
	fi

	POS=$(mpc | grep "\[" | awk '{print $3}' | sed 's/\/.*//')
	LENGTH=$(mpc | grep "\[" | awk '{print $3}' | sed 's/.*\///')
        ACTIVE=`mpc | grep '\[' | awk '{print $4}' | sed 's/(//'| sed 's/%)//'`
	INACTIVE=$((100-$ACTIVE))
	
	
        case "$COUNT" in

	"0")    outputinfo "Artist:" "$ARTIST"	
		;;
	"1")    outputinfo "Artist:" "$ARTIST"
		;;
	"2")    outputinfo "Album:" "$ALBUM"
		;;
	"3")    outputinfo "Album:" "$ALBUM"
		;;
	"4")    outputinfo "Song:" "$SONG" 
		;;
	"5")    outputinfo "Song:" "$SONG" 
		;;
	esac

	if [ "$COUNT" = "5" ]; then
	    COUNT=0
        else
	    COUNT=$(($COUNT + 1))
	fi

	# pause/playing and progress bar
	STATE=$(mpc | grep "\[" | awk '{print $1}') #check if paused
        if [ "$STATE" = "[paused]" ]; then
            echo -n "^fg(#242424)$LCOR^fg(#707070)^bg(#242424) paused^fg(#242424)      ^bg()"
        else
            echo -n "^fg(#242424)$LCOR^fg(#707070)^bg(#242424) playing^fg(#242424)     ^bg()"
        fi
#	echo "^bg(#202020)^fg(#aaaaaa)$POS  ^fg(#1874cd)^r($(($ACTIVE))x4)^fg(#000)^r("$INACTIVE"x4)^fg()^fg(#aaaaaa)  $LENGTH ^fg()^bg()^fg(#202020)$RCOR"
	echo "^bg(#242424)^fg(#aaaaaa)$POS ^fg(#707070)/^fg(#aaaaaa) $LENGTH  ^bg()^fg(#242424)$RCOR"

    fi    


done | dzen2 -x 0 -y 1148 -h 12 -w 600 -ta l -fg $SEPCOL -bg "#000000" -fn "-*-dejavu sans mono-medium-r-*-*-10-*-*-*-*-*-*-*"
