#!/bin/bash

UPDATE=1
TEXTCOL="#aaaaaa"

ONLINE_ICONCOL="#707070"
SEPCOL="#707070"

DOWNICON="^i(/home/cas/.monsterwm/dzen2/icons/down.xbm)"
UPICON="^i(/home/cas/.monsterwm/dzen2/icons/up.xbm)"
LCOR="^i(/home/cas/.xmonad/dzen2/icons/myicons/corner-left.xbm)"
RCOR="^i(/home/cas/.xmonad/dzen2/icons/myicons/corner-right.xbm)"
COUNT=0

function pad { 
    C=0
    while [ "$C" -lt $1 ]; do
	echo -n " "
	C=$(( $C + 1 ))
    done
    echo -n "^bg()"
}

function outputinfo {
    echo -n "^fg(#000000)$LCOR" # left corner
    echo -n "^bg(#000000)^fg(#707070)$1^fg()$2" # content
    pad $3
    echo -n "^fg(#000000)$RCOR" # right corner
}

sleep 2
while :;  do

    # Internet
    CON=0
    ETH0=$(ip -o addr | grep "eth0.*inet " | awk '{print $2}' | sed -e 's/\/.*//g')
    WLAN0=$(ip -o addr | grep "wlan0.*inet " | awk '{print $2}' | sed -e 's/\/.*//g')
    if [ "$ETH0" != "" ] 
	then {
		CON="$ETH0";
		CONICON="eth0";}
		INTERFACE=eth0
    elif [ "$WLAN0" != "" ]
         then {
		CON="$WLAN0";
		CONICON="wlan0";}
		INTERFACE="wlan0"
    else CON="offline"; 
    fi
	
    RXB=`cat /sys/class/net/$INTERFACE/statistics/rx_bytes`
    TXB=`cat /sys/class/net/$INTERFACE/statistics/tx_bytes`
    TOTALDOWN=$(echo "($RXB) / 1024 / 1024 / 1024" | bc -l | xargs printf "%.3f")
    TOTALUP=$(echo "($TXB) / 1024 / 1024 / 1024" | bc -l | xargs printf "%.3f")

    sleep $UPDATE

    RXBN=`cat /sys/class/net/$INTERFACE/statistics/rx_bytes`
    TXBN=`cat /sys/class/net/$INTERFACE/statistics/tx_bytes`
	
    RXR=$(echo "( $RXBN - $RXB ) / 1024" | bc -l | xargs printf "%.1f")
    TXR=$(echo "( $TXBN - $TXB ) / 1024" | bc -l | xargs printf "%.1f")
    
    echo -n "^fg(#707070)$LCOR^bg(#242424)^fg(#707070)NET:^bg()^fg(#242424)$RCOR" # main label
    
    case $COUNT in

	[0-1]) STRLEN=$(expr length "$CONICON")
	     PAD=$(( 15 - $STRLEN )) 
	     outputinfo "" "^fg($TEXTCOL)$CONICON" $PAD
	     ;;
	[2-3]) STRLEN=$(expr length "$CON")
	     PAD=$(( 15 - $STRLEN ))
	     outputinfo "" "^fg($TEXTCOL)$CON" $PAD
	     ;;
	[4-5]) STRLEN=$(expr length "DL:$TOTALDOWN")
	     PAD=$(( 13 - $STRLEN )) 
	     outputinfo "DL:" "^fg($TEXTCOL)$TOTALDOWN^fg(#707070)gB" $PAD
	     ;;
	[6-7]) STRLEN=$(expr length "UL:$TOTALUP")
	     PAD=$(( 13 - $STRLEN )) 
	     outputinfo "UL:" "^fg($TEXTCOL)$TOTALUP^fg(#707070)gB" $PAD
	     ;;
    esac
    if [ "$COUNT" = "7" ]; then
	COUNT=0
    else
	COUNT=$(( $COUNT + 1 ))
    fi
    
    STRLEN=$(expr length "$RXR")
    PAD=$(( 10 - $STRLEN ))
    outputinfo "$DOWNICON " "^fg($TEXTCOL)$RXR^fg()kB/s" $PAD
    STRLEN=$(expr length "$TXR")
    PAD=$(( 10 - $STRLEN ))
    outputinfo "$UPICON " "^fg($TEXTCOL)$TXR^fg()kB/s" $PAD
    echo ""

    RXB=$RXBN; TXB=$TXBN

done | dzen2 -x 1070 -y 1148 -h 12 -w 412 -ta l -fg $SEPCOL -bg "#000000" -fn "-*-dejavu sans mono-medium-r-*-*-10-*-*-*-*-*-*-*"
