#!/bin/bash

# for labels such as MPD, SYS ...
LABELCOL="#fffafa"
LABELWRAPCOL="#333332"
# for all dynamic information read from system
INFOCOL="#C0C0C0"
# for tags such as cpu, mem ...
TAGCOL="#deb887"
# for symbols such as mB, % ...
SYMCOL="#9d9d9d"
# bar color
BGCOL="#303030"
# bar text color
FGCOL=""
#wrapper color
WRAPCOL="#1a1a1b"


UPDATE=1
TEXTCOL="$INFOCOL"

ONLINE_ICONCOL="#1a1a1b"
SEPCOL="#1a1a1b"

DOWNICON="^i(/home/cas/.monsterwm/dzen2/icons/down.xbm)"
UPICON="^i(/home/cas/.monsterwm/dzen2/icons/up.xbm)"
LCOR="^i(/home/cas/.xmonad/dzen2/icons/myicons/corner-left.xbm)"
RCOR="^i(/home/cas/.xmonad/dzen2/icons/myicons/corner-right.xbm)"
COUNT=0

function pad { 
    C=0
    while [ "$C" -lt $1 ]; do
	echo -n " "
	C=$(( $C + 1 ))
    done
    echo -n "^bg()"
}

function outputinfo {
    echo -n "^fg($WRAPCOL)$LCOR" # left corner
    echo -n "^bg($WRAPCOL)^fg($WRAPCOL)$1^fg()$2" # content
    pad $3
    echo -n "^fg($WRAPCOL)$RCOR" # right corner
}

sleep 2
while :;  do

    # Internet
    CON=0
    ETH0=$(ip -o addr | grep "eth0.*inet " | awk '{print $2}' | sed -e 's/\/.*//g')
    WLAN0=$(ip -o addr | grep "wlan0.*inet " | awk '{print $2}' | sed -e 's/\/.*//g')
    if [ "$ETH0" != "" ] 
	then {
		CON="$ETH0";
		CONICON="eth0";}
		INTERFACE=eth0
    elif [ "$WLAN0" != "" ]
         then {
		CON="$WLAN0";
		CONICON="wlan0";}
		INTERFACE="wlan0"
    else CON="offline"; 
    fi
	
    RXB=`cat /sys/class/net/$INTERFACE/statistics/rx_bytes`
    TXB=`cat /sys/class/net/$INTERFACE/statistics/tx_bytes`
    TOTALDOWN=$(echo "($RXB) / 1024 / 1024 / 1024" | bc -l | xargs printf "%.3f")
    TOTALUP=$(echo "($TXB) / 1024 / 1024 / 1024" | bc -l | xargs printf "%.3f")

    sleep $UPDATE

    RXBN=`cat /sys/class/net/$INTERFACE/statistics/rx_bytes`
    TXBN=`cat /sys/class/net/$INTERFACE/statistics/tx_bytes`
	
    RXR=$(echo "( $RXBN - $RXB ) / 1024" | bc -l | xargs printf "%.1f")
    TXR=$(echo "( $TXBN - $TXB ) / 1024" | bc -l | xargs printf "%.1f")
    
    echo -n "^fg($LABELWRAPCOL)$LCOR^bg($LABELWRAPCOL)^fg($LABELCOL)NET:^bg()^fg($LABELWRAPCOL)$RCOR" # main label
    
    case $COUNT in

	[0-1]) STRLEN=$(expr length "If: $CON")
	     PAD=$(( 15 - $STRLEN ))
	     outputinfo "^fg($TAGCOL)If: ^fg()" "^fg($TEXTCOL)$CON" $PAD
	     ;;
	[2-3]) STRLEN=$(expr length "Dl: $TOTALDOWN")
	     PAD=$(( 13 - $STRLEN )) 
	     outputinfo "^fg($TAGCOL)Dl: ^fg()" "^fg($INFOCOL)$TOTALDOWN^fg($SYMCOL)gB" $PAD
	     ;;
	[4-5]) STRLEN=$(expr length "Ul :$TOTALUP")
	     PAD=$(( 13 - $STRLEN )) 
	     outputinfo "^fg($TAGCOL)Ul: ^fg()" "^fg($INFOCOL)$TOTALUP^fg($SYMCOL)gB" $PAD
	     ;;
    esac
    if [ "$COUNT" = "5" ]; then
	COUNT=0
    else
	COUNT=$(( $COUNT + 1 ))
    fi
    
    STRLEN=$(expr length "$RXR")
    PAD=$(( 7 - $STRLEN ))
    outputinfo "^fg($TAGCOL)$DOWNICON^fg() " "^fg($TEXTCOL)$RXR^fg()^fg($SYMCOL)kB/s^fg()" $PAD
    STRLEN=$(expr length "$TXR")
    PAD=$(( 7 - $STRLEN ))
    outputinfo "^fg($TAGCOL)$UPICON " "^fg($TEXTCOL)$TXR^fg()^fg($SYMCOL)kB/s^fg()" $PAD
    echo ""

    RXB=$RXBN; TXB=$TXBN

done | dzen2 -x 729 -y 1034 -h 12 -w 412 -ta l -fg $SEPCOL -bg $BGCOL -fn "-*-dejavu sans mono-extralight-r-*-*-9-*-*-*-*-*-*-*"
