#!/bin/bash

# sysbar.sh

# for labels such as MPD, SYS ...
LABELCOL="#fffafa"
LABELWRAPCOL="#333332"
# for all dynamic information read from system
INFOCOL="#c0c0c0"
# for tags such as cpu, mem ...
TAGCOL="#deb887"
# for symbols such as mB, % ...
SYMCOL="#9d9d9d"
# bar color
BGCOL="#303030"
# bar text color
FGCOL="#707070"
#wrapper color
WRAPCOL="#1a1a1b"

# corners for module
LCOR="^i(/home/cas/stumpwm/dzen2/icons/myicons/corner-left.xbm)"
RCOR="^i(/home/cas/stumpwm/dzen2/icons/myicons/corner-right.xbm)"

# pads text with spaces
# syntax: pad uint
function pad { 
    C=0
    while [ "$C" -lt $1 ]; do
	echo -n " "
	C=$(( $C + 1 ))
    done
    echo -n "^bg()"
}

# echo modules with content, uses pad() to keep
# syntax: ouputinfo stringAsItWillAppear stringFormatted moduleLength
function outputinfo {
        STRLEN=$(expr length "$1" )
	PAD=$(( $3 - $STRLEN ))
	echo -n "^fg($WRAPCOL)$LCOR^fg()^bg($WRAPCOL)$2^fg()"
	pad $PAD
	echo -n "^bg()^fg($WRAPCOL)$RCOR"
}

# registers time and date of boot
UPTIME=$(uptime -s | sed -e 's/-/ /g' | awk '{print $4" "$3"-"$2"-"$1}')

# prevents bar from being overdrawn
sleep 1


while true;
do

    # find app currently using most cpu
    GRABLEADER=$(top -b -n 1 | awk '/PID/{getline; print $9" "$12}')
    # register cpu consum. of leader
    LEADERUSAGE=$(echo $GRABLEADER | awk '{print $1}')
    # register leader, restrict stringlen.
    LEADER=$(echo $GRABLEADER | awk '{print $2}')
    STRLEN=$(expr length "$LEADER")
    if [ $STRLEN  -gt 8 ]; then
	LEADER="${LEADER:0:8}..."
    fi
    
    # register load avg.
    LOAD=$(uptime |  sed 's/.*://; s/ //; s/,//g')

    # register current ram usage
    MEM=$(free -m | grep "buffers/cache" | awk '{print $3}')

    # register cpu temp
    CPU=$(sensors | grep "Core 1" | awk '{print $3}' | sed -e 's/+//g' | sed -e 's/\..*//')

    # print label for SYS-bar
    echo -n "^fg($LABELWRAPCOL)$LCOR^bg($LABELWRAPCOL)^fg($LABELCOL)SYS:^bg()^fg($LABELWRAPCOL)$RCOR"
    if [ "$CPU" -lt 60 ]; then CPU="^fg($INFOCOL)$CPU"C"^fg()";
	elif [[ "$CPU" -gt 49 && "$CPU" -lt 85 ]]; then CPU="^fg(#cc6600)$CPU"C"^fg()";
        else CPU="^fg(red)$CPU"C"^fg()";
    fi

    # echo modules
    outputinfo "Cpu: $LEADER @ $LEADERUSAGE"%"" "^fg($TAGCOL)Cpu:^fg() ^fg($INFOCOL)$LEADER^fg() ^fg($SYMCOL)@^fg() ^fg($INFOCOL)$LEADERUSAGE^fg()^fg($SYMCOL)%^fg()" 24
    outputinfo "$LOAD" "^fg($INFOCOL)$LOAD" 12
    outputinfo "$CPU" "$CPU" 5
    outputinfo "Mem: $MEM"mB"" "^fg($TAGCOL)Mem:^fg() ^fg($INFOCOL)$MEM^fg()^fg($SYMCOL)mB^fg()" 12


    # newline, as required by dzen2
    echo ""

    sleep 3; # update in 3 secs

done | dzen2 -x 325 -y 1034 -h 12 -w 670 -ta l -fg $FGCOL -bg $BGCOL -fn "-*-dejavu sans mono-extralight-r-*-*-9-*-*-*-*-*-*-*"
