#!/bin/bash

# for labels such as MPD, SYS ...
LABELCOL="#fffafa"
LABELWRAPCOL="#333332"
# for all dynamic information read from system
INFOCOL="#C0C0C0"
# for tags such as cpu, mem ...
TAGCOL="#deb887"
# for symbols such as mB, % ...
SYMCOL="#9d9d9d"
# bar color
BGCOL="#303030"
# bar text color
FGCOL="#707070"
#wrapper color
WRAPCOL="#1a1a1b"

# icons
LCOR="^i(/home/cas/stumpwm/dzen2/icons/myicons/corner-left.xbm)"
RCOR="^i(/home/cas/stumpwm/dzen2/icons/myicons/corner-right.xbm)"

# update every second
UPDATE=1

# for volume bar
BARLENGTH=50

# to prevent being overdrawn by bar to the left
sleep 4

while :;  do

    # Volume
    VOL=`amixer -M sget Master | grep Mono: | awk '{print $4 $6}' | sed -e 's/\%//g' | sed -e 's/\[//' | sed -e 's/\]//' ` 	
    ON=`echo $VOL | grep "on"` 
    if [ "$ON" != "" ]; then 
	VOL=`echo $VOL | sed -e 's/\[on\]//'`;
        ACTIVE=$(($VOL / 2))
        INACTIVE=$(($BARLENGTH-$ACTIVE))
        # label
	echo -n "^fg($LABELWRAPCOL)$LCOR^bg($LABELWRAPCOL)^fg($LABELCOL)VOL:^bg()^fg($LABELWRAPCOL)$RCOR"
        # module
        echo -n "^fg($WRAPCOL)$LCOR^fg()" # left corner
        echo -n "^bg($WRAPCOL)^fg(#1874cd)^r("$ACTIVE"x6)^fg($BGCOL)^r("$INACTIVE"x6)^fg($INFOCOL) $VOL^fg()^bg()" # main area
	echo    "^fg($WRAPCOL)$RCOR" # right corner
    else # change color of 
	VOL=`echo $VOL | sed -e 's/\[off\]//'`;
        ACTIVE=$(($VOL / 2))
        INACTIVE=$(($BARLENGTH-$ACTIVE))
        # label
        echo -n "^fg($LABELWRAPCOL)$LCOR^bg($LABELWRAPCOL)^fg($LABELCOL)VOL:^bg()^fg($LABELWRAPCOL)$RCOR"
        # module
        echo -n "^fg($WRAPCOL)$LCOR^fg()" # left corner
        echo -n "^bg($WRAPCOL)^fg(#707070)^r("$ACTIVE"x6)^fg($BGCOL)^r("$INACTIVE"x6)^fg($INFOCOL) $VOL^fg()^bg()" # main area
	echo    "^fg($WRAPCOL)$RCOR" # right corner
    fi

    
    sleep $UPDATE


done | dzen2 -x 1420  -y 1034 -h 12 -w 260 -ta r -fg $FGCOL -bg $BGCOL -fn "-*-dejavu sans mono-extralight-r-*-*-9-*-*-*-*-*-*-*"
